spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

application.security.jwt.secret-key=${JWT_SECRET}


application.security.jwt.expiration=86400000


application.security.jwt.refresh-token.expiration=604800000


application.upload.logos-dir=uploads/logos
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


server.port=${PORT:8080}
server.servlet.context-path=/api

application.mail.enabled=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


application.mail.from-address=no-reply@FleetVision.com
application.mail.from-name=FleetVision - Ne pas repondre

application.otp.expiration-minutes=10